title: Hayden Michel personal portfolio
email: haydenmichel8@gmail.com
description: >-
  A website I created to show my engineering projects I have been working on at school, work, and in my personal time!
baseurl: ""
url: "https://haydenmichel8.github.io"
github_username: HaydenMichel8
linkedin_username: hayden-michel-596948290

remote_theme: "mmistakes/jekyll-theme-basically-basic@1.4.5"

plugins:
  - jekyll-remote-theme
  - jekyll-feed

sass:
  style: compressed

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
